### PR TITLE
Add Dictionnaire des Francophones

### PR DESCRIPTION
**Pull request by hugolpz**
@pamputt 

The url and verb were copy-engineered from their SPARQL's Query Service.
Screenshot from 2023-03-22 14-34-28

### CODE REVIEW

**Review by pamputt — APPROVED** [review]
I do not know how to test it. Especially where did you find the URL of DDF endpoint?
Otherwise, it looks good to me.

**Comment by pamputt** [comment]
Actually, Noé can confirm the endpoint URL for sure. If you are not sure about this URL, I let you contact him (via the Wiktionnaire if needed).

**Comment by hugolpz** [comment]
Ok. The change is barely a copy-paste of existing code, with string variations, we move ahead and merge. 🎉 
I added an example case in [Help:SPARQL/test#Francophones](https://lingualibre.org/wiki/Help:SPARQL/test#Francophones).

✅  UPDATE HAVE BEEN DEPLOYED, THIS PR IS DONE.
- https://lingualibre.org/wiki/Help:SPARQL/test

----
BUG (#7): Query to dictionnaire des francophones fails.
See : Right click > Inspect > Network > filter with `sparql`.
I suspect a config on their side, investigation via #7.

**Comment by hugolpz** [comment]
@pamputt , Noe reported me that they don't use blazegraph but another system. Maybe `format=json` in our xhr query is not the right parameter. By example, maybe their API use the word `response-format=json` or something like that. Or maybe JSON response is not currently enabled. Anyway, someone with relevant knowledge or access will have to investigate.

**Pull request merged**
